module.exports = {
	RECEIVE_BOOKS: 'RECEIVE_BOOKS',
	RECEIVE_PEOPLE: 'RECEIVE_PEOPLE',
	RECEIVE_ERROR: 'RECEIVE_ERROR',
	RECEIVE_LOANS: 'RECEIVE_LOANS',
	CHANGE_OPTION: 'CHANGE_OPTION',
	CHANGE_VIEW:	'CHANGE_VIEW',
	CHANGE_PAGE:	'CHANGE_PAGE',
	HANDLE_POST:	'HANDLE_POST'
};
